#pragma once
#include <iostream>
#include <string.h>
using namespace std ;

#include "ToolType.h"

#pragma region COMMUNICATION

enum COMM_CODE
{
	E_COMM_THROW = -1,
	E_COMM_OK,
	E_COMM_NG,
};

enum COMM232PORT
{
	E_COMM_COM1 = 0,
	E_COMM_COM2 ,
	E_COMM_COM3 ,
	E_COMM_COM4 ,
	E_COMM_COM5 ,
	E_COMM_COM6 ,
	E_COMM_COM7 ,
	E_COMM_COM8 ,
	E_COMM_COM9 ,
	E_COMM_COM10 ,
	E_COMM_COM11 ,
	E_COMM_COM12 ,
};

enum COMM232BAUDRATE
{
	E_COMM_BAUDRATE110 = 0 ,
	E_COMM_BAUDRATE300 ,
	E_COMM_BAUDRATE600 ,
	E_COMM_BAUDRATE1200 ,
	E_COMM_BAUDRATE2400 ,
	E_COMM_BAUDRATE4800 ,
	E_COMM_BAUDRATE9600 ,
	E_COMM_BAUDRATE14400 ,
	E_COMM_BAUDRATE19200 ,
	E_COMM_BAUDRATE38400 ,
	E_COMM_BAUDRATE56000 ,
	E_COMM_BAUDRATE57600 ,
	E_COMM_BAUDRATE115200 ,
	E_COMM_BAUDRATE921600 ,
};

enum COMM232PARITY
{
	E_COMM_PARITYNONE = 0 ,
	E_COMM_PARITYODD ,
	E_COMM_PARITYEVEN ,
	E_COMM_PARITYMARK ,
	E_COMM_PARITYSPACE ,
};

enum COMM232DATABITS
{
	E_COMM_DATABITS5 = 5 ,
	E_COMM_DATABITS6 ,
	E_COMM_DATABITS7 ,
	E_COMM_DATABITS8 ,
};

enum COMM232STOPBITS
{
	E_COMM_STOPONE = 0 ,
	E_COMM_STOPONEANDHALF ,
	E_COMM_STOPTWO,
};

#pragma endregion COMMUNICATION